### PR TITLE
Created the new network goodpath tests cfg file

### PR DESCRIPTION
**Pull request by PavamanSubramaniyam**
Also created the badpath scenario and vnic good path scenario files

### CODE REVIEW

**Comment by abdhaleegit** [comment]
one run log please

**Comment by PavamanSubramaniyam** [comment]
python avocado-setup.py --run-suite host_io_network_scenario_goodpath --input-file input_network_config.txt --output-dir HTX_GOODPATH
23:47:14 INFO    : Check for environment
23:47:24 INFO    :
23:47:24 INFO    : Running Host Tests Suite io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_start_htx_nic_devices
23:47:24 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start$ m /tmp/mux/io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_start_htx_nic_devices.yaml --force-job-id 185cd91ff196e994607847d469612596df4e34e3  -job-results-dir HTX_GOODPATH/results
JOB ID     : 185cd91ff196e994607847d469612596df4e34e3
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-25T23.47-185cd91/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start;run-07ab: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_start;run-07ab: PASS (1604.06 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-25T23.47-185cd91/results.html
JOB TIME   : 1615.28 s
00:14:24 INFO    :
00:14:24 INFO    :
00:14:24 INFO    : Running Host Tests Suite io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices
00:14:24 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check$ m /tmp/mux/io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.yaml --force-job-id 7c361d42c59d61add043a1c83c65cfe762d7091c  -job-results-dir HTX_GOODPATH/results
JOB ID     : 7c361d42c59d61add043a1c83c65cfe762d7091c
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.14-7c361d4/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: PASS (120.62 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.14-7c361d4/results.html
JOB TIME   : 136.41 s
00:16:49 INFO    :
00:16:49 INFO    :
00:16:49 INFO    : Running Host Tests Suite io_network_scenario_goodpath_ppc64_cpu_test_PPC64Test_test_smt_loop
00:16:49 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/ppc64_cpu_test.py:PPC64Test.test_smt_loop$ {}force-job-id af400e73d4a1369425c778143ac02b3f1477f7ed{-}  -job-results-dir HTX_GOODPATH/results
JOB ID     : af400e73d4a1369425c778143ac02b3f1477f7ed
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.16-af400e7/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/ppc64_cpu_test.py:PPC64Test.test_smt_loop: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/ppc64_cpu_test.py:PPC64Test.test_smt_loop: PASS (237.95 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.16-af400e7/results.html
JOB TIME   : 263.99 s
00:21:18 INFO    :
00:21:18 INFO    :
00:21:18 INFO    : Running Host Tests Suite io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.2
00:21:18 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check$ m /tmp/mux/io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.yaml --force-job-id 4b758b4e89feea30d6c483c31cdde7547ed15c19  -job-results-dir HTX_GOODPATH/results
JOB ID     : 4b758b4e89feea30d6c483c31cdde7547ed15c19
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.21-4b758b4/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: PASS (120.50 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.21-4b758b4/results.html
JOB TIME   : 140.77 s
00:23:47 INFO    :
00:23:47 INFO    :
00:23:48 INFO    : Running Host Tests Suite io_network_scenario_goodpath_cpustress_cpustress
00:23:48 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py m /tmp/mux/io_network_scenario_goodpath_cpustress_cpustress.yaml --force-job-id bb004e25cd806c728a3ce9627abddbeec119a372  -job-results-dir HTX_GOODPATH/results
JOB ID     : bb004e25cd806c728a3ce9627abddbeec119a372
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.23-bb004e2/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/4) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py:cpustresstest.test;run-cycles-default-type-2220: STARTED
 (1/4) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py:cpustresstest.test;run-cycles-default-type-2220: PASS (135.20 s)
 (2/4) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py:cpustresstest.test;run-cycles-default-type-cpu_serial_off_on-ff56: STARTED
 (2/4) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py:cpustresstest.test;run-cycles-default-type-cpu_serial_off_on-ff56: PASS (37.89 s)
 (3/4) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py:cpustresstest.test;run-cycles-long-type-default-1b13: STARTED
 (3/4) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py:cpustresstest.test;run-cycles-long-type-default-1b13: PASS (1290.09 s)
 (4/4) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py:cpustresstest.test;run-cycles-long-type-cpu_serial_off_on-ceb9: STARTED
 (4/4) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py:cpustresstest.test;run-cycles-long-type-cpu_serial_off_on-ceb9: PASS (360.72 s)
RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.23-bb004e2/results.html
JOB TIME   : 1884.02 s
00:55:17 INFO    :
00:55:17 INFO    :
00:55:17 INFO    : Running Host Tests Suite io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.3
00:55:17 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check$ m /tmp/mux/io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.yaml --force-job-id ddb5ee3dd9e201db57627c0fcc746ff2558747da  -job-results-dir HTX_GOODPATH/results
JOB ID     : ddb5ee3dd9e201db57627c0fcc746ff2558747da
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.55-ddb5ee3/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: PASS (120.49 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.55-ddb5ee3/results.html
JOB TIME   : 140.15 s
00:57:46 INFO    :
00:57:46 INFO    :
00:57:46 INFO    : Running Host Tests Suite io_network_scenario_goodpath_memtester
00:57:46 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/memory/memtester.py {}force-job-id 180d8ef63db135deebf13f69ea2598a6e88c4d6b{-}  -job-results-dir HTX_GOODPATH/results
Fetching asset from /root/avocado-fvt-wrapper/tests/avocado-misc-tests/memory/memtester.py:Memtester.test
JOB ID     : 180d8ef63db135deebf13f69ea2598a6e88c4d6b
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.57-180d8ef/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/memory/memtester.py:Memtester.test: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/memory/memtester.py:Memtester.test: PASS (4198.38 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T00.57-180d8ef/results.html
JOB TIME   : 4223.81 s
02:08:19 INFO    :
02:08:19 INFO    :
02:08:19 INFO    : Running Host Tests Suite io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.4
02:08:19 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check$ m /tmp/mux/io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.yaml --force-job-id a197b35850df37f0b6378af6c502c6997ba1f070  -job-results-dir HTX_GOODPATH/results
JOB ID     : a197b35850df37f0b6378af6c502c6997ba1f070
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T02.08-a197b35/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: PASS (120.51 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T02.08-a197b35/results.html
JOB TIME   : 146.17 s
02:10:55 INFO    :
02:10:55 INFO    :
02:10:55 INFO    : Running Host Tests Suite io_network_scenario_goodpath_bridge_bridge
02:10:55 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bridge.py m /tmp/mux/io_network_scenario_goodpath_bridge_bridge.yaml --force-job-id 8c16da0c7a73df86a378b9b5686611e3d11d12e8  -job-results-dir HTX_GOODPATH/results
JOB ID     : 8c16da0c7a73df86a378b9b5686611e3d11d12e8
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T02.10-8c16da0/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bridge.py:Bridging.test_bridge_create;run-1dee: STARTED
 (1/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bridge.py:Bridging.test_bridge_create;run-1dee: PASS (0.05 s)
 (2/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bridge.py:Bridging.test_bridge_run;run-1dee: STARTED
 (2/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bridge.py:Bridging.test_bridge_run;run-1dee: PASS (4.19 s)
 (3/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bridge.py:Bridging.test_bridge_delete;run-1dee: STARTED
 (3/3) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/bridge.py:Bridging.test_bridge_delete;run-1dee: PASS (0.32 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T02.10-8c16da0/results.html
JOB TIME   : 31.27 s
02:11:31 INFO    :
02:11:31 INFO    :
02:11:31 INFO    : Running Host Tests Suite io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.5
02:11:31 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check$ m /tmp/mux/io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.yaml --force-job-id 3003347a2b30f29d23e0bdda5263cfe27a922bae  -job-results-dir HTX_GOODPATH/results
JOB ID     : 3003347a2b30f29d23e0bdda5263cfe27a922bae
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T02.11-3003347/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_check;run-07ab: PASS (120.32 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T02.11-3003347/results.html
JOB TIME   : 132.72 s
02:13:48 INFO    :
02:13:48 INFO    :
02:13:48 INFO    : Running Host Tests Suite io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_stop_htx_nic_devices
02:13:48 INFO    : Running: /usr/bin/avocado run {}max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_stop$ m /tmp/mux/io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_stop_htx_nic_devices.yaml --force-job-id bfd73154ebeabbf2ea430eed3e6289f010a985b1  -job-results-dir HTX_GOODPATH/results
JOB ID     : bfd73154ebeabbf2ea430eed3e6289f010a985b1
JOB LOG    : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T02.13-bfd7315/job.log
Task exception was never retrieved
future: <Task finished coro=<StatusServer.serve_forever() done, defined at /usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py:40> exception=AttributeError("'Server' object has no attribute 'serve_forever'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/avocado_framework-100.1-py3.6.egg/avocado/core/status/server.py", line 44, in serve_forever
    await self._server_task.serve_forever()
AttributeError: 'Server' object has no attribute 'serve_forever'
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_stop;run-07ab: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net/htx_nic_devices.py:HtxNicTest.test_stop;run-07ab: PASS (5.05 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/HTX_GOODPATH/results/job-2023-04-26T02.13-bfd7315/results.html
JOB TIME   : 17.59 s
02:14:10 INFO    :
02:14:10 INFO    : Summary of test results can be found below:
TestSuite                                                                                      TestRun    Summary

host_io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_start_htx_nic_devices        Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-25T23.47-185cd91/job.log

PASS 1	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices        Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T00.14-7c361d4/job.log

PASS 1	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_ppc64_cpu_test_PPC64Test_test_smt_loop                       Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T00.16-af400e7/job.log

PASS 1	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.2      Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T00.21-4b758b4/job.log

PASS 1	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_cpustress_cpustress                                          Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T00.23-bb004e2/job.log

PASS 4	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.3      Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T00.55-ddb5ee3/job.log

PASS 1	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_memtester                                                    Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T00.57-180d8ef/job.log

PASS 1	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.4      Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T02.08-a197b35/job.log

PASS 1	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_bridge_bridge                                                Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T02.10-8c16da0/job.log

PASS 3	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_check_htx_nic_devices.5      Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T02.11-3003347/job.log

PASS 1	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
host_io_network_scenario_goodpath_htx_nic_devices_HtxNicTest_test_stop_htx_nic_devices         Run        Successfully executed
HTX_GOODPATH/results/job-2023-04-26T02.13-bfd7315/job.log

PASS 1	CANCEL 0	ERRORS 0	FAILURES 0	SKIP 0	WARN 0	INTERRUPT 0
02:14:10 INFO    : Removing temporary mux dir

**Review by abdhaleegit — CHANGES_REQUESTED** [review]
LGTM, but need a dry run logs for other cfg too

**Review by abdhaleegit — APPROVED** [review]

**Review by spoorthys1303 — APPROVED** [review]
LGTM

**Pull request merged**
