### PR TITLE
Adding required fileds to config files

### PR DESCRIPTION
**Pull request by bskjois**
Signed-off-by: Kowshik Jois B S <kowsjois@linux.ibm.com>

### CODE REVIEW

**Comment by spoorthys1303** [comment]
@bskjois Can you please describe why these configs are added now

**Comment by bskjois** [comment]
@spoorthys1303 Not sure from when this change was introduced but it is a required for a long time now. If not specified, we end up getting the below error. Hence these changes are required to be merged.

```
567 [stderr] stdout: b''
568 [stderr] stderr: b'ERROR    \n--os-variant/--osinfo OS name is required, but no value was\nset or     detected.\n\nThis is now a fatal error. Specifying an OS name is required\nfor modern, performan    t, and secure virtual machine defaults.\n\nYou can see a full list of possible OS name values wit    h:\n\n   virt-install --osinfo list\n\nIf your Linux distro is not listed, try one of generic val    ues\nsuch as: linux2022, linux2020, linux2018, linux2016\n\nIf you just need to get the old behav    ior back, you can use:\n\n  --osinfo detect=on,require=off\n\nOr export VIRTINSTALL_OSINFO_DISABL    E_REQUIRE=1\n\n'
569 [stderr] additional_info: None
```

**Comment by spoorthys1303** [comment]
LGTM

**Review by spoorthys1303 — APPROVED** [review]
LGTM

**Pull request merged**
