### PR TITLE
Added Distro  regression bucket

### PR DESCRIPTION
**Pull request by PraveenPenguin**
Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by sathnaga** [comment]
@PraveenPenguin add a dry-run log

**Comment by sacsant** [comment]
@PraveenPenguin can you change the name of config file from distro_regression to os_regression ?

**Comment by PraveenPenguin** [comment]
> @PraveenPenguin can you change the name of config file from distro_regression to os_regression ?
@sacsant sure will do

**Comment by sathnaga** [comment]
@PraveenPenguin ping

**Comment by PraveenPenguin** [comment]
closing this PR as it outdated

**Pull request closed without merging**
